Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "client-wan"
    
    config.vm.network "private_network", 
        ip: "192.168.57.10",
        netmask: "24"
end