Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "client_wan"
    
    config.vm.network "private_network", 
        ip: "192.168.64.20",
        netmask: "21"
end