Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "client"
    
    config.vm.network "private_network", 
        ip: "192.168.56.20",
        netmask: "21"
end