Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "client"
    
    config.vm.network "private_network", virtualbox__intnet: "net-56",
        ip: "192.168.56.10",
        netmask: "24"
  
    # Copie le script de test des flux réseaux
    config.vm.provision "file", source: "provision/test_flux.sh", destination: "/home/vagrant/test_flux.sh"

    config.vm.provision "shell", path: "provision/install_tools.sh"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
    end

    config.vm.provision "shell", inline: <<-SHELL
    sudo sudo ip route add 192.168.57.0/24 via 192.168.56.30
    SHELL
end