Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "firewall"
    
    config.vm.network "private_network", 
        ip: "192.168.56.30", device: "eth1", netmask: "24"
    config.vm.network "private_network", 
        ip: "192.168.57.30", device: "eth2", netmask: "24"
    
    config.vm.provision "shell", path: "provision/setup_ufw.sh"
    config.vm.provision "shell", path: "provision/routing.sh"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
    end
end