Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "server"
    
    config.vm.network "private_network", virtualbox__intnet: "net-56",
        ip: "192.168.56.20", netmask: "24"
    
    # Copie le script de test des flux réseaux
    config.vm.provision "file", source: "provision/test_flux.sh", destination: "/home/vagrant/test_flux.sh"

    config.vm.provision "shell", path: "provision/install_tools.sh"
    config.vm.provision "shell", path: "provision/install_nginx.sh"
    config.vm.provision "shell", path: "provision/setup_ufw.sh"
    config.vm.provision "shell", path: "provision/routing.sh"

    config.vm.provision "shell", inline: <<-SHELL
    sudo sudo ip route add 192.168.57.0/24 via 192.168.56.30
    SHELL

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
    end
end