Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "server"
    
    config.vm.network "private_network", 
        ip: "192.168.56.10",
        netmask: "21"
    
    # config.vm.provision "shell", path: "provision/install_nginx.sh"
    # config.vm.provision "shell", path: "provision/setup_ufw.sh"
end